name: Bug
description: Something is broken.
type: Bug
projects:
  - "jdnb1/5"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what happened and what you expected to happen
      placeholder: "Example: The form fails to submit"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Walk us through how to trigger this bug, step by step.
    validations:
      required: false
