name: Task
description: Smallest unit of work. Always a sub-issue of a Story or Bug.
type: Task
assignees: nbarger-jdnb
projects:
  - "jdnb1/5"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
    validations:
      required: true
